version: 2
jobs:
    build:
        docker:
            - image: "debian:stretch"
        steps:
            - checkout:
                path: src
            - run:
                command: apt-get update
            - run:
                command: apt-get install -y python python-pip curl git
            - run:
                command: pip install awscli
            - run:
                command: ./src/scripts/install-docker.sh
            - setup_remote_docker
            - run:
                command: docker build -t ${DOCKER_IMAGE} src/job-docker
                
