version: 2
jobs:
    build:
        docker:
            - image: "debian:stretch"
        steps:
            - run:
                name: "Install dependencies"
                command: apt-get update && apt-get install -y python python-pip curl git 
            - run:
                name: "Install aws cli"
                command: pip install awscli
            - checkout:
                path: src
            - run:
                name: "Install docker"
                command: ./src/bin/install-docker.sh
            - setup_remote_docker
            - run:
                name: "Build job docker"
                working_directory: "src"
                command: ./bin/build.sh
                
